### ISSUE TITLE
Display data on a web page from your Web Service

### ISSUE THREAD

**Issue by Spriz** [drunkenflamingos/drunkenflamingo-backend#16]

**Comment by Spriz** [comment]
@datafar @PatrickGorgin do you have any idea what web page we should show data from *our*  own web service? 🤔

**Comment by PatrickGorgin** [comment]
Not sure I understand the question? :)

**Comment by Spriz** [comment]
The assignment 3 says the following: 

>"Display data on a web page from your Web Service"

**Comment by Spriz** [comment]
@PatrickGorgin and I'm unsure exactly why we should use our own web service to show data on our own page 🤔

**Comment by PatrickGorgin** [comment]
That's just for the assignment, we don't actually have to keep it in the project if we don't want it? :)

**Comment by Spriz** [comment]
Ahhh.. clever one.
